# Generated by Django 4.2.10 on 2024-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('length', models.CharField(choices=[('30', '30 minute session'), ('45', '45 minute session'), ('60', '60 minute session'), ('75', '75 minute session'), ('90', '90 minute session'), ('120', '120 minute session')], max_length=20)),
                ('price', models.SmallIntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
