name: CodeCov
on: 
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - sprint01
    - sprint02
jobs:
  run:
    runs-on: windows-latest
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.11
    - name: Generate Report
      run: |
        pip install coverage
        coverage run manage.py test
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
